### ISSUE TITLE
"Referencing Internet-Drafts" section is slightly confusing

### ISSUE THREAD

**Issue by DavidSchinazi** [martinthomson/no-expiry#16]
It's somewhat unclear to me who the target audience of the "Referencing Internet-Drafts" section is. At first, I was assuming I was part of the target audience as a draft author. However, I write my drafts in kramdown where a reference is as simple as `See {{?NO-EXPIRY=thomson-gendispatch-no-expiry}}.`. In that scenario, I don't include the two-digit draft number - though it is added by the tooling. That's made life much better than the days of XML editing where the draft number needed to be edited manually every time idnits complained. So, is this guidance for tool authors?

Additionally, we might want to be clearer about what "URLs for the IETF Datatracker" means - the tooling currently links to the [HTMLized version from the datatracker](https://datatracker.ietf.org/doc/html/draft-thomson-gendispatch-no-expiry-02) but you could imagine linking instead to the [status page of this version of the draft](https://datatracker.ietf.org/doc/draft-thomson-gendispatch-no-expiry/02/), or perhaps the [HTML version from the archive](https://www.ietf.org/archive/id/draft-thomson-gendispatch-no-expiry-02.html).

**Comment by martinthomson** [comment]
The point of the text is primarily to address the reality of the situation.  People create artifacts that cite drafts, but they often do so inconsistently.  As you say, it is sometimes convenient to refer to a draft generically, as you often do when authoring a document.  However, you do that on the expectation that the artifacts you create as a result are fixed to a specific version.

I don't think that we need to be clearer about which of the many options on the datatracker are used.  Each is valid and the choice is up to the person making the citation.  However, the expectation is that the datatracker is the canonical reference source for I-Ds, just like rfc-editor.org is the canonical reference source for RFCs (as much as I find the info page links in RFCs annoying, it is still the right solution in the general case).

**Comment by DavidSchinazi** [comment]
> The point of the text is primarily to address the reality of the situation. People create artifacts that cite drafts, but they often do so inconsistently. As you say, it is sometimes convenient to refer to a draft generically, as you often do when authoring a document. However, you do that on the expectation that the artifacts you create as a result are fixed to a specific version.

Totally agree. I'd suggest mentioning that in the draft.

> I don't think that we need to be clearer about which of the many options on the datatracker are used. Each is valid and the choice is up to the person making the citation. However, the expectation is that the datatracker is the canonical reference source for I-Ds, just like rfc-editor.org is the canonical reference source for RFCs (as much as I find the info page links in RFCs annoying, it is still the right solution in the general case).

Fair enough, that sounds reasonable.
